import type { EventCard, LifeRun, StatMap } from "./types";
import { HYDRO_TALES } from "./tales";

/** 水信息 / 水文职场人生：贴合本站 Hydro 主线的趣味分支 */

export const HYDRO_STATS = [
  { key: "tech", label: "技术" },
  { key: "field", label: "外业" },
  { key: "write", label: "文案" },
  { key: "network", label: "人脉" },
  { key: "mood", label: "心态" },
  { key: "coin", label: "收入势" },
];

export function createHydroRun(seed = `${Date.now()}`): LifeRun {
  const stats: StatMap = {
    tech: 45 + Math.floor(Math.random() * 25),
    field: 40 + Math.floor(Math.random() * 30),
    write: 40 + Math.floor(Math.random() * 25),
    network: 35 + Math.floor(Math.random() * 30),
    mood: 50 + Math.floor(Math.random() * 25),
    coin: 35 + Math.floor(Math.random() * 25),
  };
  return {
    domainId: "hydro",
    age: 22,
    stats,
    flags: [],
    log: [],
    queue: [],
    ended: false,
    seed,
  };
}

export const HYDRO_POOL: EventCard[] = [
  {
    id: "grad_path",
    title: "毕业去向",
    blurb: "水利信息化交叉口。",
    minAge: 22,
    maxAge: 24,
    adapt: { boostIds: ["design", "code"], cutIds: ["gap"], byStats: ["tech", "write"], scale: 0.45 },
    options: [
      {
        id: "design",
        label: "设计院水文岗",
        weight: 22,
        delta: { write: 4, coin: 3, mood: -1 },
        addFlags: ["design_inst"],
        enqueue: ["first_project"],
      },
      {
        id: "code",
        label: "水务信息化开发",
        weight: 20,
        delta: { tech: 6, mood: -2, coin: 5 },
        addFlags: ["dev"],
        enqueue: ["sprint"],
      },
      {
        id: "bureau",
        label: "厅局/测站编制",
        weight: 14,
        delta: { network: 4, mood: 4, coin: 2, field: 2 },
        addFlags: ["civil_hydro"],
        enqueue: ["station_duty"],
      },
      {
        id: "master",
        label: "考研深造",
        weight: 18,
        delta: { tech: 3, write: 3, coin: -4, mood: -3 },
        addFlags: ["grad_school"],
        enqueue: ["thesis"],
      },
      { id: "gap", label: "先歇一歇", weight: 12, delta: { mood: 2, coin: -3 }, addFlags: ["gap"] },
      {
        id: "field_crew",
        label: "外业测报队",
        weight: 14,
        delta: { field: 8, mood: 1, coin: 2 },
        addFlags: ["field_crew"],
        enqueue: ["flood_season"],
      },
    ],
  },
  {
    id: "first_project",
    title: "第一个水平衡项目",
    includeFlags: ["design_inst"],
    minAge: 22,
    maxAge: 30,
    adapt: { boostIds: ["pass"], cutIds: ["rewrite"], byStats: ["write", "tech"], scale: 0.55 },
    options: [
      {
        id: "pass",
        label: "一次过审",
        weight: 14,
        delta: { write: 5, network: 3, mood: 5, coin: 4 },
        addFlags: ["report_ace"],
      },
      { id: "revise", label: "两轮修改过关", weight: 36, delta: { write: 3, mood: 1, coin: 2 } },
      {
        id: "rewrite",
        label: "被打回重写",
        weight: 28,
        delta: { mood: -6, write: 2 },
        addFlags: ["revision_hell"],
        enqueue: ["mentor_chat"],
      },
      { id: "template", label: "套模板蒙混", weight: 22, delta: { coin: 1, mood: -1, write: -2 }, addFlags: ["shortcut"] },
    ],
  },
  {
    id: "sprint",
    title: "智慧水利迭代冲刺",
    includeFlags: ["dev"],
    adapt: { boostIds: ["ship"], cutIds: ["bug"], byStats: ["tech", "mood"], scale: 0.5 },
    options: [
      { id: "ship", label: "按时上线", weight: 18, delta: { tech: 4, network: 2, mood: 3, coin: 3 }, addFlags: ["shipped"] },
      { id: "overtime", label: "通宵修 bug", weight: 30, delta: { tech: 3, mood: -5, field: -1 } },
      { id: "bug", label: "生产事故回滚", weight: 20, delta: { mood: -8, network: -3, tech: 1 }, addFlags: ["prod_incident"] },
      { id: "refactor", label: "偷偷重构祖传代码", weight: 22, delta: { tech: 5, mood: 2, coin: -1 } },
      { id: "demo", label: "领导参观演示翻车", weight: 10, delta: { mood: -4, network: -2, tech: 1 } },
    ],
  },
  {
    id: "station_duty",
    title: "测站值班夜",
    includeFlags: ["civil_hydro"],
    options: [
      { id: "calm", label: "水情平稳", weight: 40, delta: { mood: 3, field: 1 } },
      {
        id: "alarm",
        label: "超警连夜上报",
        weight: 25,
        delta: { field: 4, mood: -2, network: 3 },
        addFlags: ["flood_report"],
        enqueue: ["flood_season"],
      },
      { id: "sensor", label: "传感器失灵手测", weight: 20, delta: { field: 5, tech: 2, mood: -1 } },
      { id: "lonely", label: "山里没信号", weight: 15, delta: { mood: -3, field: 2 } },
    ],
  },
  {
    id: "thesis",
    title: "学位论文卡点",
    includeFlags: ["grad_school"],
    adapt: { boostIds: ["publish"], cutIds: ["delay"], byStats: ["tech", "write", "mood"], scale: 0.55 },
    options: [
      { id: "publish", label: "中了 SCI/核心", weight: 10, delta: { tech: 6, write: 4, mood: 6, network: 3 }, addFlags: ["published"] },
      { id: "pass", label: "顺利答辩", weight: 32, delta: { write: 3, mood: 4 }, addFlags: ["phd_ok", "design_inst"], enqueue: ["first_project"] },
      { id: "delay", label: "延期半年", weight: 28, delta: { mood: -7, coin: -3 }, addFlags: ["delay"] },
      { id: "switch", label: "改投行业就业", weight: 20, delta: { mood: 1, coin: 2 }, addFlags: ["design_inst"], enqueue: ["first_project"] },
      { id: "xaj", label: "死磕 XAJ 率定", weight: 10, delta: { tech: 8, mood: -4 }, addFlags: ["xaj_nerd"] },
    ],
  },
  {
    id: "flood_season",
    title: "汛期会战",
    minAge: 23,
    maxAge: 45,
    adapt: { boostIds: ["hero"], cutIds: ["miss"], byStats: ["field", "mood", "tech"], scale: 0.5 },
    options: [
      {
        id: "hero",
        label: "预报准确立功",
        weight: 14,
        delta: { field: 4, network: 5, mood: 5, coin: 3 },
        addFlags: ["flood_hero"],
      },
      { id: "ok", label: "平稳度汛", weight: 36, delta: { field: 2, mood: 2 } },
      { id: "miss", label: "漏报被点名", weight: 18, delta: { mood: -8, network: -4 }, addFlags: ["blamed"] },
      { id: "equip", label: "抢修测站设备", weight: 20, delta: { tech: 3, field: 3, mood: -2 } },
      { id: "model", label: "临时调模型参数", weight: 12, delta: { tech: 5, mood: -1 }, addFlags: ["model_tune"] },
    ],
  },
  {
    id: "mentor_chat",
    title: "导师/组长谈话",
    options: [
      { id: "encourage", label: "被鼓励振作", weight: 35, delta: { mood: 6, write: 1 } },
      { id: "pressure", label: "压力山大", weight: 30, delta: { mood: -4, tech: 1 } },
      { id: "resource", label: "给了好资源", weight: 20, delta: { network: 5, tech: 2, coin: 2 }, addFlags: ["mentor"] },
      { id: "quit_hint", label: "暗示换岗", weight: 15, delta: { mood: -2 }, enqueue: ["career_fork"] },
    ],
  },
  {
    id: "career_fork",
    title: "职业分叉",
    minAge: 26,
    maxAge: 40,
    adapt: { boostIds: ["lead", "startup"], cutIds: ["burnout"], byStats: ["network", "tech", "mood"], scale: 0.5 },
    options: [
      { id: "lead", label: "升项目负责人", weight: 18, delta: { network: 6, coin: 6, mood: -2, write: 2 }, addFlags: ["pm"] },
      { id: "startup", label: "合伙做水务 SaaS", weight: 10, delta: { tech: 4, coin: -5, mood: 3 }, addFlags: ["startup"] },
      { id: "gov", label: "跳槽厅局信息化", weight: 16, delta: { network: 4, mood: 3, coin: 2 }, addFlags: ["civil_hydro"] },
      { id: "stay", label: "继续深耕本岗", weight: 28, delta: { tech: 2, write: 2, mood: 1 } },
      { id: "burnout", label: "倦怠想转行", weight: 18, delta: { mood: -6 }, addFlags: ["burnout"], enqueue: ["side_project"] },
      { id: "teach", label: "去高校/培训", weight: 10, delta: { write: 4, mood: 4, coin: -2 }, addFlags: ["teacher"] },
    ],
  },
  {
    id: "side_project",
    title: "业余作品集",
    blurb: "做个流域一张图 / 水平衡生成器？",
    adapt: { boostIds: ["viral"], cutIds: ["abandon"], byStats: ["tech", "mood"], scale: 0.55 },
    options: [
      {
        id: "viral",
        label: "作品被转发",
        weight: 12,
        delta: { tech: 4, network: 6, mood: 6, coin: 2 },
        addFlags: ["portfolio_hit"],
      },
      { id: "ship_side", label: "上线自用工具", weight: 28, delta: { tech: 3, mood: 4 }, addFlags: ["side_ship"] },
      { id: "abandon", label: "鸽了三个月", weight: 30, delta: { mood: -2 } },
      { id: "oss", label: "开源水文小工具", weight: 20, delta: { tech: 5, network: 3, mood: 3 }, addFlags: ["oss"] },
      { id: "paper", label: "整理成技术博客", weight: 10, delta: { write: 4, network: 2 } },
    ],
  },
  {
    id: "conference",
    title: "行业交流会",
    minAge: 25,
    maxAge: 50,
    adapt: { boostIds: ["talk"], cutIds: ["sleep"], byStats: ["network", "write", "mood"], scale: 0.4 },
    options: [
      { id: "talk", label: "上台分享", weight: 16, delta: { network: 5, write: 3, mood: 3 }, addFlags: ["speaker"] },
      { id: "card", label: "互换名片若干", weight: 34, delta: { network: 3 } },
      { id: "sleep", label: "会场补觉", weight: 22, delta: { mood: 2, network: -1 } },
      { id: "deal", label: "谈成合作意向", weight: 14, delta: { coin: 6, network: 4 }, addFlags: ["deal"] },
      { id: "awkward", label: "提问被问懵", weight: 14, delta: { mood: -3, tech: 1 } },
    ],
  },
  {
    id: "family",
    title: "生活侧支",
    minAge: 28,
    maxAge: 45,
    excludeFlags: ["life_settled"],
    adapt: { boostIds: ["balance"], cutIds: ["overwork"], byStats: ["mood", "coin"], scale: 0.45 },
    options: [
      { id: "balance", label: "工作生活平衡", weight: 28, delta: { mood: 5 }, addFlags: ["life_settled"] },
      { id: "overwork", label: "项目压倒一切", weight: 26, delta: { coin: 5, mood: -5, field: -1 }, addFlags: ["workaholic"] },
      { id: "move", label: "调动去家乡", weight: 18, delta: { mood: 4, coin: -2, network: -2 }, addFlags: ["hometown"] },
      { id: "city", label: "扎根一线城市", weight: 20, delta: { coin: 4, mood: -2, network: 3 }, addFlags: ["tier1"] },
      { id: "partner", label: "同行成眷属", weight: 8, delta: { mood: 6, network: 2 }, addFlags: ["partner", "life_settled"] },
    ],
  },
  {
    id: "tender",
    title: "招投标之夜",
    minAge: 26,
    maxAge: 42,
    excludeFlags: ["civil_hydro", "teacher"],
    adapt: { boostIds: ["win"], cutIds: ["lose"], byStats: ["write", "network", "tech"], scale: 0.5 },
    options: [
      { id: "win", label: "中标了", weight: 16, delta: { coin: 10, network: 4, mood: 6 }, addFlags: ["won_tender"] },
      { id: "close", label: "惜败第二", weight: 28, delta: { mood: -2, write: 2, network: 1 } },
      { id: "lose", label: "陪跑出局", weight: 24, delta: { mood: -5 }, addFlags: ["lost_tender"] },
      { id: "partner", label: "联合体拿下", weight: 18, delta: { coin: 6, network: 5 }, addFlags: ["won_tender"] },
      { id: "walk", label: "主动弃标", weight: 14, delta: { mood: 1, coin: -1 } },
    ],
  },
  {
    id: "gis_night",
    title: "一张图加班夜",
    minAge: 23,
    maxAge: 38,
    adapt: { boostIds: ["ship_map"], cutIds: ["crash"], byStats: ["tech", "mood"], scale: 0.45 },
    options: [
      { id: "ship_map", label: "图层顺利上线", weight: 22, delta: { tech: 4, mood: 3 }, addFlags: ["gis_ship"] },
      { id: "crs", label: "坐标系统一战", weight: 26, delta: { tech: 3, mood: -2 } },
      { id: "crash", label: "服务挂了回滚", weight: 18, delta: { mood: -6, tech: 1 }, addFlags: ["prod_incident"] },
      { id: "beauty", label: "领导只在意配色", weight: 20, delta: { mood: -1, write: 1, network: 1 } },
      { id: "open", label: "顺手开源小插件", weight: 14, delta: { tech: 3, network: 2, mood: 2 }, addFlags: ["oss"] },
    ],
  },
  {
    id: "exam_civil",
    title: "事业编窗口",
    minAge: 24,
    maxAge: 35,
    excludeFlags: ["civil_hydro"],
    adapt: { boostIds: ["pass"], cutIds: ["fail"], byStats: ["write", "mood", "tech"], scale: 0.5 },
    options: [
      {
        id: "pass",
        label: "上岸测站/厅局",
        weight: 10,
        delta: { mood: 8, coin: 2, network: 3 },
        addFlags: ["civil_hydro"],
        enqueue: ["station_duty"],
      },
      { id: "waitlist", label: "进面未录", weight: 22, delta: { mood: -3, write: 2 } },
      { id: "fail", label: "笔试折戟", weight: 28, delta: { mood: -5 } },
      { id: "skip", label: "不考了继续干", weight: 26, delta: { tech: 2, mood: 1 } },
      { id: "later", label: "明年再战", weight: 14, delta: { write: 1, mood: -1 }, addFlags: ["exam_retry"] },
    ],
  },
  {
    id: "legacy",
    title: "十年回望",
    minAge: 40,
    maxAge: 55,
    options: [
      {
        id: "lead_org",
        label: "带团队做平台",
        weight: 22,
        delta: { network: 6, tech: 2, mood: 4, coin: 5 },
        addFlags: ["org_lead"],
      },
      { id: "expert", label: "成为领域专家", weight: 24, delta: { tech: 6, write: 4, mood: 3 }, addFlags: ["expert"] },
      { id: "quiet", label: "安稳测站日子", weight: 28, delta: { mood: 5, field: 2 }, addFlags: ["quiet_life"] },
      { id: "regret", label: "有点后悔当初选择", weight: 14, delta: { mood: -4 }, enqueue: ["career_fork"] },
      { id: "mentor_young", label: "带新人传帮带", weight: 12, delta: { mood: 6, write: 2, network: 2 } },
    ],
  },
  ...HYDRO_TALES,
];
