import type { EventCard, LifeRun, StatMap } from "./types";

/** 凡人重开：借鉴 BitLife / 人生重开模拟器 — 年龄段事件池 + 属性门槛 + flag 长程 */

export const MORTAL_STATS = [
  { key: "iq", label: "智力" },
  { key: "str", label: "体质" },
  { key: "spr", label: "精神" },
  { key: "chr", label: "魅力" },
  { key: "money", label: "家境" },
  { key: "lif", label: "寿命势" },
];

export function createMortalRun(seed = `${Date.now()}`): LifeRun {
  const stats: StatMap = {
    iq: 40 + Math.floor(Math.random() * 40),
    str: 40 + Math.floor(Math.random() * 40),
    spr: 40 + Math.floor(Math.random() * 40),
    chr: 40 + Math.floor(Math.random() * 40),
    money: 30 + Math.floor(Math.random() * 50),
    lif: 70 + Math.floor(Math.random() * 25),
  };
  return {
    domainId: "mortal",
    age: 0,
    stats,
    flags: [],
    log: [],
    queue: [],
    ended: false,
    seed,
  };
}

export const MORTAL_POOL: EventCard[] = [
  {
    id: "birth_talent",
    title: "天赋觉醒",
    blurb: "开局特质（人生重开式）。",
    minAge: 0,
    maxAge: 3,
    adapt: { boostIds: ["genius", "athlete"], cutIds: ["sickly"], byStats: ["iq", "str"], scale: 0.45 },
    options: [
      { id: "genius", label: "神童", weight: 8, delta: { iq: 12, spr: 4 }, addFlags: ["gifted"] },
      { id: "athlete", label: "体魄过人", weight: 12, delta: { str: 12, lif: 3 }, addFlags: ["athletic"] },
      { id: "charm", label: "万人迷胚子", weight: 14, delta: { chr: 12 }, addFlags: ["cute"] },
      { id: "rich", label: "含着金钥匙", weight: 10, delta: { money: 20 }, addFlags: ["rich_kid"] },
      { id: "ordinary", label: "普通宝宝", weight: 40, delta: { spr: 2 } },
      { id: "sickly", label: "体弱多病", weight: 16, delta: { str: -8, lif: -5, spr: -3 }, addFlags: ["frail"] },
    ],
  },
  {
    id: "kindergarten",
    title: "幼儿园风云",
    minAge: 3,
    maxAge: 6,
    options: [
      { id: "leader", label: "当上小班长", weight: 18, delta: { chr: 4, spr: 2 }, addFlags: ["leader_seed"] },
      { id: "fight", label: "抢玩具大战", weight: 22, delta: { str: 2, spr: -1 } },
      { id: "draw", label: "画了一墙涂鸦", weight: 28, delta: { iq: 1, chr: 2 } },
      { id: "cry", label: "哭闹被抱走", weight: 20, delta: { spr: -2 }, addFlags: ["shy"] },
      { id: "nap", label: "午睡第一名", weight: 12, delta: { lif: 1, spr: 1 } },
    ],
  },
  {
    id: "primary",
    title: "小学日常",
    minAge: 7,
    maxAge: 12,
    adapt: { boostIds: ["top"], cutIds: ["bully_lose"], byStats: ["iq", "spr"], scale: 0.5 },
    options: [
      { id: "top", label: "年级前三", weight: 12, delta: { iq: 5, spr: 2 }, addFlags: ["study_ace"], enqueue: ["olympiad"] },
      { id: "sports", label: "运动会摘金", weight: 16, delta: { str: 5, chr: 2 }, addFlags: ["sports_kid"] },
      { id: "friend", label: "交到死党", weight: 24, delta: { spr: 4, chr: 2 }, addFlags: ["bestie"] },
      { id: "bully_lose", label: "被欺负忍了", weight: 18, delta: { spr: -4, str: -1 }, addFlags: ["bullied"] },
      { id: "game", label: "沉迷网吧", weight: 14, delta: { iq: -2, str: -2, spr: 1 }, addFlags: ["gamer"] },
      { id: "avg", label: "平平无奇一学期", weight: 30 },
    ],
  },
  {
    id: "olympiad",
    title: "奥数集训营",
    blurb: "需学霸 flag；智力抬高获奖权重。",
    minAge: 10,
    maxAge: 15,
    includeFlags: ["study_ace"],
    requireStats: { iq: 55 },
    adapt: { boostIds: ["gold"], cutIds: ["quit"], byStats: ["iq", "spr"], scale: 0.6 },
    options: [
      { id: "gold", label: "省一等奖", weight: 10, delta: { iq: 6, spr: 3, money: 2 }, addFlags: ["contest_gold"] },
      { id: "silver", label: "市二等奖", weight: 22, delta: { iq: 3, spr: 1 } },
      { id: "burnout", label: "刷题抑郁", weight: 18, delta: { spr: -8, iq: 2 }, addFlags: ["burnout"] },
      { id: "quit", label: "中途摆烂", weight: 20, delta: { spr: 2, iq: -1 }, removeFlags: ["study_ace"] },
    ],
  },
  {
    id: "middle_crush",
    title: "初中暗恋",
    minAge: 13,
    maxAge: 15,
    adapt: { boostIds: ["confess_ok"], cutIds: ["reject"], byStats: ["chr", "spr"], scale: 0.55 },
    options: [
      {
        id: "confess_ok",
        label: "告白成功",
        weight: 14,
        delta: { spr: 8, chr: 3 },
        addFlags: ["first_love"],
        enqueue: ["date_park"],
      },
      { id: "reject", label: "被婉拒", weight: 22, delta: { spr: -6 }, addFlags: ["heartbroken"] },
      { id: "silent", label: "埋在心里", weight: 34, delta: { spr: -1, iq: 1 } },
      { id: "focus", label: "专心中考", weight: 30, delta: { iq: 3, spr: 1 }, addFlags: ["exam_focus"] },
    ],
  },
  {
    id: "date_park",
    title: "公园约会",
    includeFlags: ["first_love"],
    minAge: 13,
    maxAge: 18,
    options: [
      { id: "nice", label: "气氛正好", weight: 40, delta: { spr: 4, chr: 2 } },
      { id: "awkward", label: "尬聊翻车", weight: 35, delta: { spr: -2, chr: -1 } },
      { id: "rain", label: "淋雨生病", weight: 25, delta: { str: -4, spr: 1, lif: -1 } },
    ],
  },
  {
    id: "gaokao",
    title: "高考命运",
    minAge: 17,
    maxAge: 20,
    excludeFlags: ["grad", "work_early", "abroad"],
    adapt: {
      boostIds: ["qingbei", "985"],
      cutIds: ["fail"],
      byStats: ["iq", "spr"],
      scale: 0.7,
    },
    options: [
      {
        id: "qingbei",
        label: "清北级别录取",
        weight: 4,
        delta: { iq: 4, spr: 6, money: -2 },
        addFlags: ["uni_top", "grad"],
        enqueue: ["college_major"],
      },
      {
        id: "985",
        label: "985/211",
        weight: 14,
        delta: { iq: 2, spr: 4 },
        addFlags: ["uni_good", "grad"],
        enqueue: ["college_major"],
      },
      {
        id: "ordinary",
        label: "普通本科",
        weight: 32,
        delta: { spr: 2 },
        addFlags: ["uni_ok", "grad"],
        enqueue: ["college_major"],
      },
      {
        id: "vocational",
        label: "专科/就业",
        weight: 22,
        delta: { money: 2, spr: -1 },
        addFlags: ["work_early"],
        enqueue: ["first_job"],
      },
      {
        id: "fail",
        label: "发挥失常复读",
        weight: 18,
        delta: { spr: -8, iq: 1 },
        addFlags: ["retry"],
      },
      { id: "abroad", label: "出国读预科", weight: 10, delta: { money: -15, chr: 3, iq: 2 }, addFlags: ["abroad", "grad"] },
    ],
  },
  {
    id: "college_major",
    title: "大学专业",
    includeFlags: ["grad"],
    excludeFlags: ["picked_major"],
    minAge: 18,
    maxAge: 23,
    options: [
      { id: "cs", label: "计算机", weight: 22, delta: { iq: 4 }, addFlags: ["maj_cs", "picked_major"], enqueue: ["intern"] },
      { id: "hydro", label: "水利/水文", weight: 12, delta: { iq: 2, str: 1 }, addFlags: ["maj_hydro", "picked_major"], enqueue: ["intern"] },
      { id: "med", label: "医学", weight: 10, delta: { iq: 5, spr: -2, lif: 2 }, addFlags: ["maj_med", "picked_major"] },
      { id: "art", label: "艺术设计", weight: 14, delta: { chr: 5, money: -2 }, addFlags: ["maj_art", "picked_major"] },
      { id: "biz", label: "经管", weight: 20, delta: { money: 3, chr: 2 }, addFlags: ["maj_biz", "picked_major"], enqueue: ["intern"] },
      { id: "undecided", label: "先混日子", weight: 22, delta: { spr: 1 }, addFlags: ["picked_major"] },
    ],
  },
  {
    id: "intern",
    title: "暑期实习",
    minAge: 19,
    maxAge: 24,
    includeFlags: ["picked_major"],
    adapt: { boostIds: ["offer"], cutIds: ["ghost"], byStats: ["iq", "chr", "money"], scale: 0.45 },
    options: [
      { id: "offer", label: "转正 offer", weight: 16, delta: { money: 8, spr: 4 }, addFlags: ["job_ready"] },
      { id: "learn", label: "学到真本事", weight: 28, delta: { iq: 3, spr: 2 } },
      { id: "overwork", label: "加班到崩溃", weight: 24, delta: { spr: -6, str: -3 }, addFlags: ["overwork"] },
      { id: "ghost", label: "被放鸽子", weight: 18, delta: { spr: -4, money: -1 } },
      { id: "startup", label: "跟老板创业梦", weight: 14, delta: { money: -4, spr: 3 }, addFlags: ["startup_seed"] },
    ],
  },
  {
    id: "first_job",
    title: "第一份工作",
    minAge: 20,
    maxAge: 28,
    excludeFlags: ["employed"],
    adapt: { boostIds: ["bigtech", "civil"], cutIds: ["unemployed"], byStats: ["iq", "chr", "money"], scale: 0.5 },
    options: [
      { id: "bigtech", label: "大厂入职", weight: 10, delta: { money: 15, spr: -3 }, addFlags: ["employed", "corp"] },
      { id: "civil", label: "考上编制", weight: 8, delta: { money: 6, spr: 5, lif: 3 }, addFlags: ["employed", "civil"] },
      { id: "sme", label: "中小公司", weight: 28, delta: { money: 5, spr: 1 }, addFlags: ["employed"] },
      { id: "freelance", label: "自由职业", weight: 16, delta: { money: 2, spr: 3, chr: 2 }, addFlags: ["employed", "freelance"] },
      { id: "unemployed", label: "暂时躺平", weight: 20, delta: { money: -4, spr: -2, lif: 1 }, addFlags: ["gap"] },
      {
        id: "hydro_job",
        label: "进水务/设计院",
        weight: 12,
        delta: { money: 6, iq: 2 },
        addFlags: ["employed", "hydro_career"],
      },
    ],
  },
  {
    id: "marriage",
    title: "婚恋节点",
    minAge: 25,
    maxAge: 40,
    excludeFlags: ["married"],
    adapt: { boostIds: ["marry"], cutIds: ["forever_single"], byStats: ["chr", "money", "spr"], scale: 0.55 },
    options: [
      { id: "marry", label: "步入婚姻", weight: 22, delta: { spr: 6, money: -5 }, addFlags: ["married"] },
      { id: "long", label: "长期恋爱", weight: 26, delta: { spr: 3 }, addFlags: ["dating"] },
      { id: "break", label: "分手疗伤", weight: 20, delta: { spr: -5 }, addFlags: ["divorced_heart"] },
      { id: "forever_single", label: "专注事业", weight: 32, delta: { money: 4, spr: -1 }, addFlags: ["career_first"] },
    ],
  },
  {
    id: "midlife",
    title: "中年课题",
    minAge: 38,
    maxAge: 55,
    adapt: { boostIds: ["promote", "health"], cutIds: ["crisis"], byStats: ["money", "spr", "str"], scale: 0.5 },
    options: [
      { id: "promote", label: "升职加薪", weight: 18, delta: { money: 12, spr: 2 }, addFlags: ["promoted"] },
      { id: "health", label: "开始养生", weight: 22, delta: { str: 4, lif: 5, spr: 2 }, addFlags: ["healthy"] },
      { id: "crisis", label: "中年危机", weight: 20, delta: { spr: -10, money: -3 }, addFlags: ["crisis"] },
      { id: "invest", label: "理财暴富？", weight: 12, delta: { money: 20, spr: 4 }, addFlags: ["lucky"] },
      { id: "invest_fail", label: "理财归零", weight: 14, delta: { money: -18, spr: -6 }, addFlags: ["broke"] },
      { id: "teach", label: "带徒弟/教学", weight: 14, delta: { spr: 4, chr: 2 } },
    ],
  },
  {
    id: "elder",
    title: "晚年回望",
    minAge: 60,
    maxAge: 90,
    options: [
      { id: "peace", label: "安稳幸福", weight: 30, delta: { spr: 8, lif: 2 }, addFlags: ["peaceful"] },
      { id: "travel", label: "环球旅居", weight: 20, delta: { money: -8, spr: 6, chr: 2 } },
      { id: "lonely", label: "略感孤独", weight: 22, delta: { spr: -4 }, addFlags: ["lonely"] },
      { id: "legacy", label: "写回忆录", weight: 18, delta: { iq: 2, spr: 5 }, addFlags: ["memoir"] },
      { id: "illness", label: "小病缠身", weight: 10, delta: { str: -8, lif: -10, spr: -3 } },
    ],
  },
  {
    id: "random_luck",
    title: "意外惊喜",
    minAge: 16,
    maxAge: 70,
    excludeFlags: ["had_lottery"],
    options: [
      { id: "lottery", label: "中了小奖", weight: 8, delta: { money: 25, spr: 6 }, addFlags: ["had_lottery"] },
      { id: "mentor", label: "遇贵人", weight: 18, delta: { iq: 2, money: 4, spr: 3 }, addFlags: ["mentor"] },
      { id: "pet", label: "养了猫狗", weight: 28, delta: { spr: 5, money: -2 }, addFlags: ["pet"] },
      { id: "scam", label: "差点被骗", weight: 22, delta: { money: -6, spr: -3, iq: 1 } },
      { id: "nothing", label: "相安无事", weight: 40 },
    ],
  },
  {
    id: "city_move",
    title: "迁徙抉择",
    minAge: 22,
    maxAge: 40,
    excludeFlags: ["settled_city"],
    adapt: { boostIds: ["tier1"], cutIds: ["hometown"], byStats: ["money", "chr", "spr"], scale: 0.4 },
    options: [
      { id: "tier1", label: "扎根一线", weight: 22, delta: { money: 6, spr: -3, chr: 2 }, addFlags: ["settled_city", "tier1"] },
      { id: "new1", label: "去新一线", weight: 28, delta: { money: 3, spr: 1 }, addFlags: ["settled_city"] },
      { id: "hometown", label: "回老家发展", weight: 24, delta: { spr: 4, money: -2, lif: 2 }, addFlags: ["settled_city", "hometown"] },
      { id: "nomad", label: "数字游民", weight: 14, delta: { chr: 3, money: -1, spr: 2 }, addFlags: ["settled_city", "nomad"] },
      { id: "wait", label: "再观望一年", weight: 12, delta: { spr: -1 } },
    ],
  },
  {
    id: "side_hustle",
    title: "副业风潮",
    minAge: 24,
    maxAge: 45,
    includeFlags: ["employed"],
    adapt: { boostIds: ["hit"], cutIds: ["scam"], byStats: ["iq", "chr", "money"], scale: 0.45 },
    options: [
      { id: "hit", label: "副业成气候", weight: 12, delta: { money: 12, spr: 3 }, addFlags: ["side_hit"] },
      { id: "learn", label: "学到新技能", weight: 30, delta: { iq: 3, spr: 1 } },
      { id: "burn", label: "精力透支", weight: 26, delta: { spr: -5, str: -2 }, addFlags: ["overwork"] },
      { id: "scam", label: "踩了坑", weight: 18, delta: { money: -8, spr: -3 } },
      { id: "skip", label: "专心本职", weight: 14, delta: { money: 2 } },
    ],
  },
  {
    id: "parent_care",
    title: "家庭责任",
    minAge: 32,
    maxAge: 55,
    adapt: { boostIds: ["balance"], cutIds: ["guilt"], byStats: ["spr", "money", "str"], scale: 0.4 },
    options: [
      { id: "balance", label: "兼顾得体", weight: 28, delta: { spr: 3, money: -3 }, addFlags: ["filial"] },
      { id: "remote", label: "远程尽孝", weight: 26, delta: { money: -2, spr: -1 } },
      { id: "guilt", label: "力不从心", weight: 24, delta: { spr: -6 }, addFlags: ["guilt"] },
      { id: "together", label: "接来同住", weight: 14, delta: { spr: 4, money: -5, lif: 1 }, addFlags: ["filial"] },
      { id: "sibling", label: "手足分担", weight: 8, delta: { spr: 2 }, addFlags: ["sibling_help"] },
    ],
  },
  {
    id: "health_check",
    title: "体检报告",
    minAge: 30,
    maxAge: 80,
    adapt: { boostIds: ["fine"], cutIds: ["warn"], byStats: ["str", "lif"], scale: 0.5 },
    options: [
      { id: "fine", label: "一切正常", weight: 35, delta: { spr: 3, lif: 2 } },
      { id: "warn", label: "指标预警", weight: 30, delta: { spr: -2, str: -2 }, addFlags: ["health_warn"], enqueue: ["lifestyle"] },
      { id: "sick", label: "需要休养", weight: 20, delta: { str: -6, lif: -4, money: -4 }, addFlags: ["ill"] },
      { id: "gym", label: "立flag去健身", weight: 15, delta: { str: 3, spr: 2 }, addFlags: ["gym"] },
    ],
  },
  {
    id: "lifestyle",
    title: "生活方式调整",
    includeFlags: ["health_warn"],
    options: [
      { id: "quit_smoke", label: "戒掉熬夜", weight: 40, delta: { str: 5, lif: 4, spr: 2 }, removeFlags: ["health_warn"] },
      { id: "ignore", label: "不当回事", weight: 35, delta: { lif: -5, spr: 1 }, addFlags: ["ignore_health"] },
      { id: "spa", label: "养生套餐", weight: 25, delta: { money: -6, str: 3, spr: 3 }, removeFlags: ["health_warn"] },
    ],
  },
];
