/** 凡人 / 水职场 / 都市夜谈 —— 趣味长尾事件（合理有趣优先） */
import type { EventCard } from "./types";

export const MORTAL_TALES: EventCard[] = [
  {
    id: "stranger_umbrella",
    title: "雨幕里的伞",
    blurb: "你忘了带伞。有人把半边天空分给你。",
    minAge: 8,
    maxAge: 70,
    options: [
      { id: "chat", label: "一路聊到车站", weight: 28, delta: { spr: 5, chr: 2 }, addFlags: ["kind_stranger"] },
      { id: "silent", label: "安静共撑，道谢分手", weight: 34, delta: { spr: 3 } },
      { id: "pay", label: "硬塞红包被拒绝", weight: 18, delta: { money: -1, spr: 2, chr: 1 } },
      { id: "run", label: "害羞跑掉，鞋全湿了", weight: 20, delta: { spr: -1, str: -1 } },
    ],
  },
  {
    id: "night_market",
    title: "夜市灯火",
    minAge: 14,
    maxAge: 45,
    adapt: { boostIds: ["feast"], cutIds: ["fight"], byStats: ["chr", "money", "spr"], scale: 0.35 },
    options: [
      { id: "feast", label: "把好吃的摊位吃成地图", weight: 30, delta: { spr: 5, money: -3, str: -1 } },
      { id: "friend", label: "偶遇老友拼桌", weight: 24, delta: { spr: 6, chr: 2 }, addFlags: ["reunion"] },
      { id: "fight", label: "为插队理论起来", weight: 16, delta: { spr: -3, chr: -1 } },
      { id: "photo", label: "拍灯火发了条冷门爆款", weight: 14, delta: { chr: 3, spr: 2 }, addFlags: ["mini_viral"] },
      { id: "early", label: "买杯热饮早早回家", weight: 16, delta: { spr: 2, lif: 1 } },
    ],
  },
  {
    id: "viral_clip",
    title: "意外上热搜（小号）",
    blurb: "你只是随口哼了两句。算法比你认真。",
    minAge: 16,
    maxAge: 50,
    excludeFlags: ["mini_viral"],
    adapt: { boostIds: ["ride"], cutIds: ["delete"], byStats: ["chr", "spr"], scale: 0.45 },
    options: [
      { id: "ride", label: "顺着浪花再创作", weight: 18, delta: { chr: 6, money: 4, spr: 3 }, addFlags: ["mini_viral", "creator"] },
      { id: "shy", label: "关掉通知装死", weight: 32, delta: { spr: 1, chr: 2 }, addFlags: ["mini_viral"] },
      { id: "delete", label: "连夜删光痕迹", weight: 22, delta: { spr: -2 }, addFlags: ["ghosted_fame"] },
      { id: "cash", label: "接了三天恰饭广告", weight: 16, delta: { money: 10, spr: -3, chr: 1 }, addFlags: ["mini_viral"] },
      { id: "teach", label: "开直播教哼歌（离谱）", weight: 12, delta: { chr: 4, money: 2, spr: 2 }, addFlags: ["creator"] },
    ],
  },
  {
    id: "bookstore",
    title: "独立书店的午后",
    minAge: 17,
    maxAge: 60,
    options: [
      { id: "novel", label: "买下厚厚一本小说", weight: 30, delta: { iq: 2, spr: 3, money: -2 } },
      { id: "talk", label: "和店员聊成书友", weight: 22, delta: { chr: 3, spr: 3 }, addFlags: ["book_friend"] },
      { id: "nap", label: "在角落被文字催眠", weight: 20, delta: { spr: 4, str: 1 } },
      { id: "steal_glance", label: "偷看隔壁的阅读清单", weight: 16, delta: { iq: 1, chr: 1 } },
      { id: "empty", label: "空手离开，口袋比心满", weight: 12, delta: { spr: 2 } },
    ],
  },
  {
    id: "inheritance",
    title: "远房亲戚的信",
    minAge: 25,
    maxAge: 55,
    excludeFlags: ["had_inheritance"],
    options: [
      { id: "cash", label: "收到一笔意外遗产", weight: 10, delta: { money: 30, spr: 5 }, addFlags: ["had_inheritance", "lucky"] },
      { id: "house", label: "继承一套需要修的老屋", weight: 14, delta: { money: -8, spr: 2, lif: 1 }, addFlags: ["had_inheritance", "old_house"] },
      { id: "debt", label: "信里其实是债务通知", weight: 18, delta: { money: -12, spr: -5 }, addFlags: ["had_inheritance"] },
      { id: "photo", label: "只有一盒旧照片", weight: 28, delta: { spr: 4, iq: 1 }, addFlags: ["had_inheritance"] },
      { id: "ignore", label: "当成诈骗没拆", weight: 30, delta: { spr: 0 }, addFlags: ["had_inheritance"] },
    ],
  },
  {
    id: "pet_rescue",
    title: "路边的小生命",
    minAge: 10,
    maxAge: 65,
    excludeFlags: ["pet"],
    adapt: { boostIds: ["adopt"], cutIds: ["walk"], byStats: ["spr", "money"], scale: 0.4 },
    options: [
      { id: "adopt", label: "带回家，日子多了一双眼睛", weight: 26, delta: { spr: 7, money: -3 }, addFlags: ["pet"] },
      { id: "shelter", label: "送到救助站并做志愿者", weight: 24, delta: { spr: 4, chr: 2 }, addFlags: ["volunteer"] },
      { id: "feed", label: "定点投喂，做流浪猫保镖", weight: 22, delta: { spr: 3, money: -1 }, addFlags: ["street_feeder"] },
      { id: "walk", label: "心软却不敢负责", weight: 28, delta: { spr: -2 } },
    ],
  },
  {
    id: "power_out",
    title: "整栋楼停电的夜",
    minAge: 12,
    maxAge: 70,
    options: [
      { id: "candle", label: "蜡烛、扑克、邻居笑声", weight: 32, delta: { spr: 5, chr: 2 }, addFlags: ["neighbor"] },
      { id: "walk", label: "下楼散步看满天星", weight: 28, delta: { spr: 4, str: 1 } },
      { id: "anxious", label: "焦虑刷手机耗尽电量", weight: 22, delta: { spr: -3 } },
      { id: "write", label: "摸黑写了半篇日记", weight: 18, delta: { iq: 2, spr: 3 } },
    ],
  },
  {
    id: "judge_fork",
    title: "命运小声提问",
    blurb: "不是考试，是镜子。",
    minAge: 20,
    maxAge: 50,
    adapt: { boostIds: ["brave"], cutIds: ["safe"], byStats: ["spr", "chr", "iq"], scale: 0.5 },
    options: [
      { id: "brave", label: "去赴一场没把握的邀约", weight: 22, delta: { spr: 4, chr: 3 }, addFlags: ["took_leap"], enqueue: ["night_market"] },
      { id: "safe", label: "把勇气留给明天", weight: 30, delta: { spr: 1, money: 1 } },
      { id: "help", label: "先去帮别人一把", weight: 24, delta: { spr: 5, chr: 2 }, addFlags: ["helper"] },
      { id: "create", label: "关上门做一件作品", weight: 24, delta: { iq: 3, spr: 2 }, addFlags: ["maker"] },
    ],
  },
  {
    id: "reunion_class",
    title: "同学聚会",
    minAge: 28,
    maxAge: 50,
    adapt: { boostIds: ["glow"], cutIds: ["compare"], byStats: ["chr", "money", "spr"], scale: 0.45 },
    options: [
      { id: "glow", label: "坦然讲述自己的普通", weight: 28, delta: { spr: 5, chr: 2 } },
      { id: "compare", label: "陷入隐形攀比", weight: 24, delta: { spr: -5, money: -1 } },
      { id: "reconnect", label: "找回一个真正说得上话的人", weight: 22, delta: { spr: 6, chr: 2 }, addFlags: ["bestie"] },
      { id: "leave", label: "中场离席去看夜景", weight: 16, delta: { spr: 2 } },
      { id: "toast", label: "敬过去那个不懂事的自己", weight: 10, delta: { spr: 4, iq: 1 } },
    ],
  },
];

export const HYDRO_TALES: EventCard[] = [
  {
    id: "excel_war",
    title: "Excel 与模型的战争",
    blurb: "有人信仰单元格，有人信仰微分方程。",
    minAge: 23,
    maxAge: 40,
    adapt: { boostIds: ["bridge"], cutIds: ["flame"], byStats: ["tech", "write", "mood"], scale: 0.45 },
    options: [
      { id: "bridge", label: "做个对照表让两边和解", weight: 26, delta: { tech: 3, write: 3, network: 3, mood: 3 }, addFlags: ["peacemaker"] },
      { id: "model", label: "坚持上模型，结果说话", weight: 22, delta: { tech: 5, mood: -2 } },
      { id: "excel", label: "先交付表格稳住场面", weight: 24, delta: { write: 2, coin: 1, tech: -1 } },
      { id: "flame", label: "群里吵到表情包战争", weight: 16, delta: { mood: -5, network: -2 }, addFlags: ["team_drama"] },
      { id: "coffee", label: "请全员喝咖啡休战", weight: 12, delta: { mood: 4, coin: -2, network: 2 } },
    ],
  },
  {
    id: "leader_visit",
    title: "领导突然来基层",
    minAge: 24,
    maxAge: 48,
    options: [
      { id: "show", label: "演示做得又稳又好看", weight: 22, delta: { network: 5, mood: 3, tech: 1 }, addFlags: ["noticed"] },
      { id: "honest", label: "把困难如实汇报", weight: 26, delta: { network: 2, mood: 1, write: 2 } },
      { id: "chaos", label: "投影仪临时罢工", weight: 20, delta: { mood: -4, tech: 1 }, enqueue: ["mentor_chat"] },
      { id: "field", label: "拉去测站看真实水情", weight: 18, delta: { field: 3, network: 3, mood: 2 } },
      { id: "hide", label: "把自己藏在屏幕后面", weight: 14, delta: { mood: -1 } },
    ],
  },
  {
    id: "missing_data",
    title: "关键数据失踪案",
    blurb: "硬盘灯在闪，像在否认一切。",
    minAge: 23,
    maxAge: 42,
    adapt: { boostIds: ["recover"], cutIds: ["panic"], byStats: ["tech", "mood"], scale: 0.5 },
    options: [
      { id: "recover", label: "从备份里捞回灵魂", weight: 24, delta: { tech: 4, mood: 4 }, addFlags: ["backup_hero"] },
      { id: "rebuild", label: "连夜重跑预处理", weight: 26, delta: { tech: 3, mood: -3, field: 1 } },
      { id: "panic", label: "先恐慌，再恐慌", weight: 20, delta: { mood: -7 }, enqueue: ["mentor_chat"] },
      { id: "ask", label: "厚着脸皮去要源数据", weight: 18, delta: { network: 3, mood: -1 } },
      { id: "lesson", label: "事后写下血泪备份规范", weight: 12, delta: { write: 3, tech: 2, mood: 1 }, addFlags: ["process_improver"] },
    ],
  },
  {
    id: "river_poem",
    title: "巡河路上的黄昏",
    minAge: 23,
    maxAge: 50,
    options: [
      { id: "photo", label: "拍下河面，当屏保", weight: 30, delta: { mood: 5, field: 1 } },
      { id: "note", label: "记下可疑的岸坡迹象", weight: 26, delta: { field: 3, tech: 1, mood: 1 }, addFlags: ["sharp_eye"] },
      { id: "chat", label: "和当地大爷聊水文年", weight: 22, delta: { network: 3, mood: 3 } },
      { id: "rain", label: "被阵雨淋成落汤鸡", weight: 14, delta: { mood: -2, field: 2 } },
      { id: "think", label: "想通一个模型边界条件", weight: 8, delta: { tech: 4, mood: 2 } },
    ],
  },
  {
    id: "banquet",
    title: "行业晚宴的圆桌",
    minAge: 26,
    maxAge: 50,
    adapt: { boostIds: ["connect"], cutIds: ["overdrink"], byStats: ["network", "mood"], scale: 0.4 },
    options: [
      { id: "connect", label: "交换到关键名片", weight: 26, delta: { network: 6, mood: 2 }, addFlags: ["connector"] },
      { id: "listen", label: "多听少说，收获情报", weight: 28, delta: { network: 3, tech: 1 } },
      { id: "overdrink", label: "推杯换盏过头", weight: 18, delta: { mood: -4, network: 1 }, addFlags: ["hangover"] },
      { id: "slip", label: "说错一句行话", weight: 14, delta: { mood: -3, network: -1 } },
      { id: "early", label: "礼貌离场去赶代码", weight: 14, delta: { tech: 2, mood: 1 } },
    ],
  },
  {
    id: "open_day",
    title: "科普开放日",
    blurb: "小朋友问：河为什么不往上流？",
    minAge: 25,
    maxAge: 55,
    options: [
      { id: "inspire", label: "讲得孩子们眼睛发亮", weight: 28, delta: { mood: 5, write: 3, network: 2 }, addFlags: ["science_comm"] },
      { id: "demo", label: "用小水槽做汇流实验", weight: 24, delta: { tech: 2, mood: 3, field: 1 } },
      { id: "stuck", label: "被问倒，诚实说不知道", weight: 22, delta: { mood: 1, write: 1 } },
      { id: "viral", label: "片段被家长拍成短视频", weight: 14, delta: { network: 4, mood: 3 }, addFlags: ["mini_famous"] },
      { id: "tired", label: "嗓子哑了，心却暖", weight: 12, delta: { mood: 4, field: -1 } },
    ],
  },
];

/** 都市夜谈：短、跳、荒诞但温柔 */
export const NIGHT_STATS = [
  { key: "luck", label: "运气" },
  { key: "nerve", label: "胆识" },
  { key: "soft", label: "柔软" },
  { key: "edge", label: "锋芒" },
  { key: "coin", label: "零钱" },
  { key: "dawn", label: "熬夜值" },
];

export const NIGHT_POOL: EventCard[] = [
  {
    id: "night_start",
    title: "城市把灯打开",
    blurb: "你站在人行道牙上，像站在一本书的扉页。",
    minAge: 18,
    maxAge: 22,
    options: [
      { id: "wander", label: "没有目的地地走", weight: 30, delta: { soft: 4, dawn: 2 }, addFlags: ["walker"] },
      { id: "bar", label: "推开一扇吵闹的门", weight: 22, delta: { nerve: 3, coin: -3, dawn: 3 }, addFlags: ["night_owl"] },
      { id: "home", label: "回家煮面", weight: 28, delta: { soft: 3, dawn: -1, luck: 1 } },
      { id: "call", label: "给很久没联系的人打电话", weight: 20, delta: { soft: 5, nerve: 2 }, addFlags: ["reached_out"] },
    ],
  },
  {
    id: "rooftop",
    title: "天台风很大",
    minAge: 19,
    maxAge: 40,
    adapt: { boostIds: ["promise"], cutIds: ["retreat"], byStats: ["nerve", "soft"], scale: 0.45 },
    options: [
      { id: "promise", label: "对风许下一个不切实际的愿", weight: 26, delta: { nerve: 4, soft: 3 }, addFlags: ["made_wish"] },
      { id: "photo", label: "拍下城市的网格", weight: 24, delta: { edge: 3, soft: 1 } },
      { id: "retreat", label: "恐高发作下楼", weight: 22, delta: { nerve: -2, soft: 1 } },
      { id: "talk", label: "遇到同样上来透气的人", weight: 18, delta: { soft: 5, luck: 2 }, addFlags: ["rooftop_friend"], enqueue: ["dawn_train"] },
      { id: "smoke_free", label: "戒掉一个坏习惯当作门票", weight: 10, delta: { dawn: -3, soft: 2, luck: 2 }, addFlags: ["quit_bad"] },
    ],
  },
  {
    id: "dawn_train",
    title: "末班车或首班车",
    blurb: "分不清结束与开始，车门一样开合。",
    minAge: 18,
    maxAge: 45,
    options: [
      { id: "sleep", label: "靠着窗子睡过两站", weight: 30, delta: { dawn: 2, soft: 2 } },
      { id: "read", label: "读完一章逃走的小说", weight: 26, delta: { edge: 2, soft: 2 } },
      { id: "miss", label: "看错站名，多走了人间一截", weight: 22, delta: { luck: 3, nerve: 1, coin: -1 }, addFlags: ["detour"] },
      { id: "help", label: "帮人抬行李上楼", weight: 22, delta: { soft: 4, nerve: 1 }, addFlags: ["helper"] },
    ],
  },
  {
    id: "coin_laundry",
    title: "自助洗衣房哲学",
    minAge: 20,
    maxAge: 45,
    options: [
      { id: "wait", label: "看滚筒旋转，像看银河", weight: 34, delta: { soft: 4, dawn: 1 } },
      { id: "chat", label: "和等衣服的人交换城市秘密", weight: 24, delta: { soft: 3, luck: 2, nerve: 1 } },
      { id: "forgot", label: "洗完忘了取，第二天更香", weight: 18, delta: { luck: 1, soft: -1 } },
      { id: "poem", label: "在收据背面写两行诗", weight: 24, delta: { edge: 3, soft: 3 }, addFlags: ["wrote_poem"] },
    ],
  },
  {
    id: "fortune",
    title: "便利店关东煮审判",
    blurb: "夜班店员问：要辣吗？这是哲学问题。",
    minAge: 18,
    maxAge: 50,
    adapt: { boostIds: ["spicy"], cutIds: ["sweet"], byStats: ["nerve", "dawn"], scale: 0.35 },
    options: [
      { id: "spicy", label: "要辣，配一罐冰汽水", weight: 28, delta: { nerve: 3, dawn: 2, coin: -2 } },
      { id: "sweet", label: "要甜，配热牛奶", weight: 28, delta: { soft: 3, dawn: -1, coin: -2 } },
      { id: "share", label: "分给门口的流浪猫", weight: 20, delta: { soft: 5, coin: -2 }, addFlags: ["cat_ally"] },
      { id: "all", label: "全要，明天的胃自己负责", weight: 14, delta: { luck: 2, dawn: 3, coin: -4 } },
      { id: "none", label: "只买电池，饿着走", weight: 10, delta: { nerve: 1, coin: -1 } },
    ],
  },
  {
    id: "night_end",
    title: "天亮之前",
    minAge: 30,
    maxAge: 55,
    options: [
      { id: "keep", label: "决定把夜晚当成副业灵感", weight: 26, delta: { edge: 4, soft: 2, dawn: 2 }, addFlags: ["night_keeper"] },
      { id: "sleep_schedule", label: "终于和作息和解", weight: 30, delta: { dawn: -5, soft: 4, luck: 2 }, addFlags: ["sleep_peace"] },
      { id: "move", label: "搬家到更安静的街区", weight: 20, delta: { soft: 3, coin: -6, luck: 1 }, addFlags: ["moved"] },
      { id: "book", label: "把夜谈写成薄薄一本", weight: 14, delta: { edge: 5, soft: 3 }, addFlags: ["wrote_book"] },
      { id: "smile", label: "对镜子说：再乱也挺好", weight: 10, delta: { soft: 5, nerve: 2, luck: 2 } },
    ],
  },
];
